SCHEMA=CARE_OAB
CONNECTION_STRING=Data Source=192.168.66.193:1521/orcl;PASSWORD=8886544832;USER ID=CARE_OAB
# SCHEMA=CARE_SIB
# CONNECTION_STRING=Data Source=192.168.66.195:1521/orcl;PASSWORD=CARE_SIB123;USER ID=CARE_SIB

PROVIDER_NAME=Oracle.ManagedDataAccess.Client
TARGET_DATABASE=ORACLE

# URLS
CARE_API_BASE_URL = http://localhost:91/CARE_API
OTHER_API_BASE_URL=http://localhost:91/CARE_RRS_API

DEFAULT_WSL_URL=http://localhost/CARE4WSL
CARE_WSL_URL=http://localhost:91/CARE_WSL

#-----CAPAD I NTERNAL----------

# SCHEMA=dbo
# # CONNECTION_STRING=Data Source=SHAIKFARUQ\\SHAIKFARUQ;Initial Catalog=CapAd;User ID=sa;Password=Surya@123;TrustServerCertificate=True
# CONNECTION_STRING=Data Source=SHAIKF\\MSSQLSERVER2019;Initial Catalog=CARE;User ID=USER;Password=Surya@123;TrustServerCertificate=True

# PROVIDER_NAME=System.Data.SqlClient
# TARGET_DATABASE=SQLSERVER

# # URLS
# CARE_API_BASE_URL = http://localhost:91/CARE_API
# OTHER_API_BASE_URL=http://localhost:91/CARE_RRS_API

# DEFAULT_WSL_URL=http://localhost/CARE4WSL
# CARE_WSL_URL=http://localhost:91/CARE_WSL


# -----Handle in JSON files----------

# PL_PATH=D:\\TestCapAd\\WEB\\PL\\
# WSL_PATH= D:\\TestCapAd\\WEB\\WSL\\
# CARE_WEBAPI_PATH=D:\\TestCapAd\\Batches\\WebApi\\

# ---------------- RRS TEST ENVIRONMENT ----------------

# SCHEMA=dbo
# CONNECTION_STRING=Data Source=192.168.66.12;Initial Catalog=RRS_TEST;User ID=RRS_TEST;Password=RRS_TEST123;TrustServerCertificate=True
# PROVIDER_NAME=System.Data.SqlClient
# TARGET_DATABASE=SQLSERVER

# # URLS
# OTHER_API_BASE_URL=http://localhost:91/CARE_API

# # Since all Keys are mandatory we need to Keep it with Dummy values
# CARE_API_BASE_URL = http://localhost:91/dummy_api

# # Default WSL URL will be replaced with CARE_WSL_URL
# DEFAULT_WSL_URL=http://localhost/RRS5WSL
# CARE_WSL_URL=http://localhost:91/CARE_WSL

