name: Phase 1 - Learn Runner

on:
  push:
    branches:
      - main

jobs:
  first-job:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Modify File
        shell: powershell
        run: |
          Add-Content hello.txt "Updated by GitHub Actions"
        
      - name: Read File
        shell: powershell
        run: |
          Get-Content hello.txt
