name: Phase 1 - Learn Runner

on:
  push:
    branches:
      - main

jobs:
  first-job:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello Faruq!"

      - name: Display File
        run: cat hello.txt

      - name: Show Current Directory
        run: pwd

      - name: List Repository Files
        run: ls -la

      - name: Show Current User
        run: whoami

      - name: Show Operating System
        run: uname -a

      - name: Show Java Version
        run: java -version

      - name: Show Git Version
        run: git --version
