name: Phase 1 - Learn Runner

on:
  push:
    branches:
      - main

jobs:
  first-job:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create Deployment Folder
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force D:\DeployDemo
          
      - name: Start IIS Pools
        shell: powershell
        run: ./scripts/StartPools.ps1

