name: Run Postman Collection

on:
  workflow_dispatch:

jobs:
  run-postman:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Node Version
        run: node -v

      - name: Check NPM Version
        run: npm -v

      - name: Install Newman
        run: npm install -g newman

      - name: Check Newman Version
        run: newman -v
        
      - name: Execute Collection
        run: |
          newman run postman/collections/CreateUser.postman_collection.json `
            -e postman/environments/UAT.postman_environment.json `
            --insecure
